<% raise("Please create \".env.#{Rails.env}\" from the provided sample file!") unless ENV['DB_ENV_POSTGRESQL_DB'] || ENV['DB_NAME'] %>
<%= Rails.env %>:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || ENV['DB_HOST'] %>
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || ENV['DB_PORT'] %>
  pool: 5
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || ENV['DB_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || ENV['DB_PASSWORD'] %>
