development:
  adapter: postgresql
  database: woo-map-development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
