# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 729856b553f85fdf0d7f6a8ea0c2bc20be721532ba8487d09d7ed6ddef60e6711635ec1834ca9c100b0e8bc9c3642abc48932ef69b6489234092aa29b5392f46

test:
  secret_key_base: f2f8b95122b53dbaf8820d3e0fd8926b3c8206fbb83902b8bc9f6d1fee8130ca42355bf5a002a3d51358a333ccac9df2eb0098e4791455d346a3878d6453b91e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
